#!/bin/bash

### BEGIN INIT INFO
# Provides:             player_state
# Required-Start:       $local_fs $remote_fs $network $time
# Required-Stop:        $local_fs $remote_fs $network $time
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    player count
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin  
DAEMON=/root/workspace/foxlog/player_state
LOGFILE=/var/log/foxlog.log
PIDFILE=/var/run/foxlog.pid
NAME=player_state



test -x $DAEMON || exit 1
. /lib/lsb/init-functions     

case $1 in
    start)
        log_daemon_msg "Start ${NAME}"
        pidofproc -p $PIDFILE $NAME $NAME > \
            /dev/null && log_success_msg " $NAME alrealy running!" && exit 0   
        start-stop-daemon -m --start --pidfile $PIDFILE --startas $DAEMON 2>&1 $LOGFILE 
        pid=$(/bin/pidof -o %PPID -x $NAME -s)
        echo $pid > $PIDFILE
        log_end_msg $?   
        ;;
    stop)
        log_daemon_msg "Stopping ${NAME}"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        log_end_msg $?
        ;;
    status)
        status_of_proc -p $PIDFILE $NAME $NAME && exit $?
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        log_action_msg "Usage: $0 {start|stop|status|restart}"
esac
exit 0